### ISSUE TITLE
Declarative data based approach?

### ISSUE THREAD

**Issue by jasonkuhrt** [prisma/prisma-label-sync#62]
Hey @maticzav 👋 started looking into this project tonight. Have you thought about a declarative data approach? Something that is just data (e.g. `yaml`), which is then processed by the label-sync cli.

For example:

```yml
colors:
  bad: '#...'
  good: '#...'
  neutral: '#...'
  # ...

labels:
  bug:
    label: type/bug
    color: bad
    tags: ['core', 'type']
  feature:
    label: type/feat
    color: good
    tags: ['core', 'type']
  docs_scope:
    label: scope/docs
    color: good
    tags: ['core', 'scope']    
  # ...     

repos:
  prisma:
    nexus:
      - use: core
      # ...
  # ...
```

**Comment by jasonkuhrt** [comment]
I also think the tool should keep a state file. When the user changes their declaration, the tool can use the state file to diff.

**Comment by maticzav** [comment]
@jasonkuhrt I like the idea of a state file. Regarding the declarative approach, I don't entirely understand what you mean with "declarative" since we are generating an object representation, and only pushing it to the `GitHub`. Besides that, the initial plan was that we could leverage the TS autocompletion and imports. The other weak point I see with the single-file approach is that the file could get very long very quickly. Maybe we could change from the TS-only approach to TS-generate-YAML approach.

I'll add the ideas to the feature list of the more Saas version of  `label-sync` that I am currently working on.

**Comment by jasonkuhrt** [comment]
> Regarding the declarative approach, I don't entirely understand what you mean with "declarative" since we are generating an object representation, and only pushing it to the GitHub.

Yeah my wording was not quite right, its indeed declarative in many ways already. I guess my point is more that, working with the entire TS toolchain feels like a heavyweight declarative. TS concepts like exporting/importing/merging are too low level I think.

One benefit of your approach is that sharing & packages is free. But support yaml consumption from deps wouldn't be a huge leap I think either.

> Besides that, the initial plan was that we could leverage the TS autocompletion and imports

JSON Schema can provide this to some degree. I don't know how reflective it can get though. Might require some level of JSON Schema generation.

> The other weak point I see with the single-file approach is that the file could get very long very quickly

Funny, I see this is a benefit. But maybe at a huge scale it would be desirable. I think it would be trivial to have the tool glob up a set of YAML files, split by some sensible patterns.

I think if this repo was boiled down to a single root `labels.yml` or whatever, that would be as simple as we can get.

> Maybe we could change from the TS-only approach to TS-generate-YAML approach.

Hm, not sure what that means/could look like? 🤔

**Comment by maticzav** [comment]
@jasonkuhrt love the comments! Thanks for clearing it out.

> Maybe we could change from the TS-only approach to TS-generate-YAML approach.
> > Hm, not sure what that means/could look like? 🤔

What I had in mind was making it possible for developers to use `YAML` as is, or they could use TS, which would generate the final `YAML` file for them.

One other question that I have: how do you feel about having defaults imposed on the repositories? With that, I mean having a "default"/match-everything-else parameter in the configuration file. What I am curious about is whether you would rather see the default label stack be applied to a newly created repository right away, or, instead, have to explicitly either push the config again or specify the exact repository names included in the sync.

**Comment by jasonkuhrt** [comment]
> which would generate the final YAML file for them.

As a user, why do I want generated YAML? What do I do with it?

> how do you feel about having defaults imposed on the repositories? With that, I mean having a "default"/match-everything-else parameter in the configuration file. What I am curious about is whether you would rather see the default label stack be applied to a newly created repository right away, or, instead, have to explicitly either push the config again or specify the exact repository names included in the sync.

Hm, special rules around back-porting isn't a feature I have a use-case for. Going back to my YAML example, what I do want is the power of regex to match on repos. A snippet from that example:

```yml
# ...
repos:
  prisma:
    nexus:
      - use: bar # ref by key name
      - useTagged: foo # ref by tag
      - label: qux # inline definition
        # ...
    .*: # regex-based matching
      - useTagged: core
```

In the above `.*` means all repos and the rule applied there is `useTagged: core` so all labels I've defined tagged with `core`.

In the above, `nexus` is also valid regexp. it would be important I think to imply `^` prefix and `$` suffix so that `nexus` does not accidentally imply `nexus-prisma` etc. If I wanted that as a user I'd just do: `nexus.*`.
